# Generated by Django 6.1.1 on 2026-09-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthstate',
            old_name='code_veerifier',
            new_name='code_verifier',
        ),
        migrations.AlterField(
            model_name='telegramloginstate',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramotp',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
