# Generated by Django 6.1.1 on 2026-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_promocode_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
