# Generated by Django 6.1.1 on 2026-09-23 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_stock_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('promo_code', ''), _negated=True), models.Q(('status', 'cancelled'), _negated=True)), fields=('user', 'promo_code'), name='unique_active_user_promo_code'),
        ),
    ]
